name: Spire-GNSS
channels:
  - conda-forge
dependencies:
  - cartopy
  - h5py
  - lxml
  - matplotlib
  - netCDF4
  - notebook
  - numpy
  - pip
  - pyproj
  - python>=3.6
  - python-dateutil
  - pyyaml
  - scipy
  - setuptools_scm
