name: spire-docs
channels:
  - conda-forge
dependencies:
  - docutils<0.18
  - fontconfig
  - freetype
  - graphviz
  - lxml
  - matplotlib
  - netCDF4
  - notebook
  - numpy
  - numpydoc
  - pip
  - pyproj
  - python>=3.6
  - python-dateutil
  - scipy
  - setuptools_scm
  - sphinx
  - sphinx-argparse
  - sphinx_rtd_theme
  - texlive-core
  - pip:
    - ..
